sudo: false
language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- pypy
branches:
  only:
  - master
  - doc/sphinxdoc
before_script:
- pip install coveralls
- "./build.py install_dependencies -v"
script:
- "./build.py -v -X analyze install"
after_success:
- coveralls --verbose
#before_deploy: "deactivate"
#deploy:
#  skip_cleanup: true
#  provider: pypi
#  user: pybuilder-travis
#  password:
#    secure: ...
#  on:
#    branch: master
#    repo: pybuilder/pybuilder
